service: galaxy-monitoring

provider:
  name: aws
  runtime: nodejs4.3
  profile: perso
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

functions:
  post:
    handler: src/groupPerfs.post
    events:
      - http:
          path: group-perfs
          method: POST
          integration: lambda
          cors: true
          request:
            template:
              application/json: '{ "body": $input.json(''$'') }'
    memorySize: 128

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: galaxy-monitoring-groupPerfs
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
