service: galaxy-monitoring

provider:
  name: aws
  runtime: nodejs4.3
  profile: perso
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

functions:
  get:
    handler: src/groupPerfs.get
    events:
      - http:
          path: group-perfs
          method: GET
          integration: lambda
          cors: true
    memorySize: 128
  getStats:
    handler: src/groupPerfs.stats
    events:
      - http:
          path: group-perfs/stats
          method: GET
          integration: lambda
          cors: true
    memorySize: 128
  create:
    handler: src/groupPerfs.create
    events:
      - http:
          path: group-perfs
          method: POST
          integration: lambda
          cors: true
          request:
            template:
              application/json: '{ "ip": "$context.identity.sourceIp", "userAgent" : "$context.identity.userAgent", "body": $input.json(''$'') }'
    memorySize: 128

resources:
  Resources:
    groupPerfs:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: galaxy-monitoring-groupPerfs
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
